from typing import Protocol, runtime_checkable


@runtime_checkable
class EventTransport(Protocol):
    def publish(self, stream: str, data: dict) -> None: ...
    def read(self, stream: str, group: str, consumer: str, batch_size: int, block_ms: int) -> list[tuple[str, dict]]: ...
    def ack(self, stream: str, group: str, msg_id: str) -> None: ...
    def ensure_group(self, stream: str, group: str) -> None: ...
    def reconnect(self) -> None: ...
